before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  image: docker:20.10.18
  stage: build
  services:
    - docker:20.10.18-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    IMAGE_TAG: $CI_REGISTRY_IMAGE:1.0.0
    IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  script:
    #- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build  -t $IMAGE_TAG_LATEST -t $IMAGE_TAG -f ./.docker/Dockerfile .
    - docker push $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG

