version: "3.7"

services:
    server:
        container_name: server
        build:
            context: .
            dockerfile: .docker/Dockerfile_dev
        image: livipst2/app

        ports:
            - '8080:80'
        environment:
            CONTAINER_ROLE: app
        env_file: ./.env
        volumes:
            - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./laravel_app:/var/www/laravel_app
#            - '.:/var/www'
            - /var/www/laravel_app/vendor

networks:
    my-duplicati-net:
        external: true
        name: custom_network

volumes:
    db: