version: "3.7"

services:
    server:
        container_name: server
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: livipst2/app
        ports:
            - '8080:80'
        environment:
            CONTAINER_ROLE: app
            WATCHTOWER_CLEANUP: "true"
        env_file: .env
        networks:
            - my-duplicati-net

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - WATCHTOWER_CLEANUP="true"
            - WATCHTOWER_POLL_INTERVAL=120  # Check for updates every 2 minutes
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_NOTIFICATION_EMAIL_FROM}
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_NOTIFICATION_EMAIL_TO}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY=false
        networks:
            - my-duplicati-net

networks:
    my-duplicati-net:
        external: true
        name: custom_network

volumes:
    db: