version: "3.7"

services:
    server:
        container_name: server
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: livipst2/app
        ports:
            - '8080:80'
        environment:
            CONTAINER_ROLE: app
            WATCHTOWER_CLEANUP: "true"
        env_file: .env
        networks:
            - my-duplicati-net

    mysql-db:
        image: 'mariadb:11.1'
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret_pass
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: dnwf_db
            MYSQL_USER: root
            MYSQL_PASSWORD: secret_pass
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
#            - /Users/admin/vol/mysql:/var/lib/mysql
            - db:/var/lib/mysql
        networks:
            - my-duplicati-net
        labels:
            - "com.centurylinklabs.watchtower.enable=false"


    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: mysql-db
            PMA_PORT: 3306
            UPLOAD_LIMIT: 200M
        ports:
            - "8081:80"
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
        networks:
            - my-duplicati-net

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - WATCHTOWER_CLEANUP="true"
            - WATCHTOWER_POLL_INTERVAL=120  # Check for updates every 2 minutes
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_NOTIFICATION_EMAIL_FROM}
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_NOTIFICATION_EMAIL_TO}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TLS_SKIP_VERIFY=false
        networks:
            - my-duplicati-net

networks:
    my-duplicati-net:
        external: true
        name: custom_network

volumes:
    db: