export const dataInvoice = [
    {
        id: 2,
        passenger_id: 3,
        driver_id: 6,
        trip_id: 7,
        rating: 4,
        notes: "Tuyet voi",
        on_time: true,
        professional: false,
        devoted: true,
        clean: false,
        deleted_at: null,
        created_at: "2023-11-24T09:49:05.000000Z",
        updated_at: "2023-11-24T09:49:05.000000Z",
        trip: {
            id: 7,
            passenger_id: 3,
            passenger_name: null,
            passenger_phone: "0909111114",
            driver_id: 6,
            driver_name: "Nguyen van C",
            driver_phone: "0974564412",
            reference: "TR000007",
            vehicle_id: null,
            product_id: null,
            product_name: null,
            notes: null,
            type: null,
            status: 7,
            total: null,
            total_discount: null,
            total_distance: 101410,
            total_duration: 9087,
            total_paid: 421000,
            deleted_at: null,
            created_at: "2023-11-23T09:06:36.000000Z",
            updated_at: "2023-11-23T09:15:16.000000Z",
            cancel_type: null,
            payment_type: 1,
            passenger_uuid: "9a9a266d-d517-4259-baae-c33cb0d0230b",
            driver_uuid: "9a9fbb66-01fd-4275-bfdd-3e04189c2cc1",
            total_insurance: null,
            trip_locations: [
                {
                    id: 13,
                    trip_id: 7,
                    address_id: null,
                    address: "cong ty",
                    province_id: null,
                    province_name: null,
                    district_id: null,
                    district_name: null,
                    ward_id: null,
                    ward_name: null,
                    lng: "106.68155700938",
                    lat: "10.752641387071",
                    type: 1,
                    created_at: null,
                    updated_at: null
                },
                {
                    id: 14,
                    trip_id: 7,
                    address_id: null,
                    address: "Nha tui",
                    province_id: null,
                    province_name: null,
                    district_id: null,
                    district_name: null,
                    ward_id: null,
                    ward_name: null,
                    lng: "107.09812511097",
                    lat: "10.346704530854",
                    type: 2,
                    created_at: null,
                    updated_at: null
                }
            ],
            trip_vehicle_types: [
                {
                    id: 21,
                    trip_id: 7,
                    vehicle_type_id: 1,
                    price: 421000,
                    distance: 101410,
                    duration: 9087,
                    total_price: null,
                    type: null,
                    status: null,
                    created_at: "2023-11-23T09:06:36.000000Z",
                    updated_at: "2023-11-23T09:06:36.000000Z",
                }
            ]
        },
        trip_locations: [],
        trip_vehicle_type: [
            {
                id: 13,
                trip_id: 7,
                address_id: null,
                address: "cong ty",
                province_id: null,
                province_name: null,
                district_id: null,
                district_name: null,
                ward_id: null,
                ward_name: null,
                lng: "106.68155700938",
                lat: "10.752641387071",
                type: 1,
                created_at: null,
                updated_at: null
            },
            {
                id: 14,
                trip_id: 7,
                address_id: null,
                address: "Nha tui",
                province_id: null,
                province_name: null,
                district_id: null,
                district_name: null,
                ward_id: null,
                ward_name: null,
                lng: "107.09812511097",
                lat: "10.346704530854",
                type: 2,
                created_at: null,
                updated_at: null
            }
        ],
        trip_location: [
            {
                id: 13,
                trip_id: 7,
                address_id: null,
                address: "728 Đ. Võ Văn Kiệt, Phường 1, Quận 5, Thành phố Hồ Chí Minh, Việt Nam",
                province_id: null,
                province_name: null,
                district_id: null,
                district_name: null,
                ward_id: null,
                ward_name: null,
                lng: "106.68155700938",
                lat: "10.752641387071",
                type: 1,
                created_at: null,
                updated_at: null
            },
            {
                id: 14,
                trip_id: 7,
                address_id: null,
                address: "972 Quang Trung, Phường 8, Gò Vấp, Thành phố Hồ Chí Minh, Việt Nam",
                province_id: null,
                province_name: null,
                district_id: null,
                district_name: null,
                ward_id: null,
                ward_name: null,
                lng: "107.09812511097",
                lat: "10.346704530854",
                type: 2,
                created_at: null,
                updated_at: null
            }
        ],
        driver: {
            id: 6,
            reference: "GC04NDQEZ",
            phone: "0974564412",
            name: "Nguyen van C",
            sex: 0,
            birth_date: null,
            total_trip: 0,
            total_use_point: 0,
            level: 0,
            level_point: 0,
            status: 2,
            type: 1,
            medias: [],
            uuid: "9a9fbb66-01fd-4275-bfdd-3e04189c2cc1",
            email: null,
            driver_type: 1,
            citizen_identify: "038343509901",
            citizen_name: "Nguyen",
            citizen_issued_date: "2021-12-21",
            citizen_expire_date: "2024-12-21",
            driver_license: "038343509901",
            driver_name: "Nguyen",
            driver_class: "A1",
            driver_issued_date: "2003-03-08",
            driver_expire_date: null,
            support_phone: null,
            support_name: null,
            created_at: "2023-11-16T04:19:05.000000Z",
            updated_at: "2023-12-07T04:14:23.000000Z",
            rating_averate: 4,
            total_ratings: 1,
            is_submit_form: true,
            place_of_origin: "Tp Ho Chi Minh",
            place_of_residence: "728 Võ Văn Kiệt, phường 1, quận 5, TPHCM",
            is_receive_ride: true,
            vehicle: {
                id: 1,
                driver_id: 6,
                vehicle_brand_id: 1,
                vehicle_type_id: 1,
                driver_phone: "0974564412",
                driver_reference: "GC04NDQEZ",
                name: null,
                description: null,
                reference: "GC04NDQEZ_VH_0001",
                is_owner: 1,
                license_plates: "60B8-04544",
                registration_certificate: "026253",
                frame_number: "808AY-218896",
                engine_number: "F27E-0259146",
                brand_name: "Honda",
                model_name: "AirBlade",
                model_years: 2010,
                color: "Đen-Xám",
                seats: 2,
                insurance_civil_accident_date: "2021-12-21",
                insurance_civil_accident_price: 50000,
                insurance_vehicle_material_date: "2021-12-21",
                insurance_vehicle_material_price: 50000,
                cudidi_insurance_civil_accident_date: null,
                cudidi_insurance_vehicle_material_date: null,
                type: 1,
                status: 1,
                medias: null,
                created_at: "2023-11-29T10:53:05.000000Z",
                updated_at: "2023-11-29T10:53:05.000000Z",
                deleted_at: null
            },
            status_name: "Bổ sung hồ sơ",
            driver_type_name: "Xe máy"
        },
        passenger: {
            id: 3,
            reference: "027569",
            phone: "0909111114",
            name: null,
            sex: null,
            birth_date: null,
            level: 0,
            level_point: 0,
            status: 1,
            type: 1,
            medias: [
                {
                    id: 113,
                    path: "https://test.api.cuvietnam.com.vn/mediaService/storage/passengers/1700737342_Sk3iC9GsLojKsuXTMwmr11eSrVSPUsWQ8ZH7NZ35.jpg",
                    type: "cover"
                }
            ],
            created_at: "2023-11-13T09:43:23.000000Z",
            updated_at: "2023-12-18T06:28:34.000000Z",
            uuid: "9a9a266d-d517-4259-baae-c33cb0d0230b",
            email: null
        }
    },
    {
        id: 3,
        passenger_id: 2,
        driver_id: 6,
        trip_id: 2,
        rating: 5,
        notes: null,
        on_time: false,
        professional: false,
        devoted: false,
        clean: false,
        deleted_at: null,
        created_at: null,
        updated_at: null,
        trip: {
            id: 2,
            passenger_id: 3,
            passenger_name: null,
            passenger_phone: "0909111114",
            driver_id: null,
            driver_name: null,
            driver_phone: null,
            reference: "TR000002",
            vehicle_id: null,
            product_id: null,
            product_name: null,
            notes: null,
            type: null,
            status: 7,
            total: null,
            total_discount: null,
            total_distance: 97771,
            total_duration: 7831,
            total_paid: 890000,
            deleted_at: null,
            created_at: "2023-11-21T08:12:40.000000Z",
            updated_at: "2023-11-21T08:15:54.000000Z",
            cancel_type: null,
            payment_type: 1,
            passenger_uuid: null,
            driver_uuid: null,
            total_insurance: null,
            trip_locations: [
                {
                    id: 3,
                    trip_id: 2,
                    address_id: null,
                    address: "cong ty",
                    province_id: null,
                    province_name: null,
                    district_id: null,
                    district_name: null,
                    ward_id: null,
                    ward_name: null,
                    lng: "106.68155700938",
                    lat: "10.752641387071",
                    type: 1,
                    created_at: null,
                    updated_at: null
                },
                {
                    id: 4,
                    trip_id: 2,
                    address_id: null,
                    address: "Nha tui",
                    province_id: null,
                    province_name: null,
                    district_id: null,
                    district_name: null,
                    ward_id: null,
                    ward_name: null,
                    lng: "107.09812511097",
                    lat: "10.346704530854",
                    type: 2,
                    created_at: null,
                    updated_at: null
                }
            ],
            trip_vehicle_types: []
        },
        trip_locations: [],
        trip_vehicle_type: [
            {
                id: 3,
                trip_id: 2,
                address_id: null,
                address: "cong ty",
                province_id: null,
                province_name: null,
                district_id: null,
                district_name: null,
                ward_id: null,
                ward_name: null,
                lng: "106.68155700938",
                lat: "10.752641387071",
                type: 1,
                created_at: null,
                updated_at: null
            },
            {
                id: 4,
                trip_id: 2,
                address_id: null,
                address: "Nha tui",
                province_id: null,
                province_name: null,
                district_id: null,
                district_name: null,
                ward_id: null,
                ward_name: null,
                lng: "107.09812511097",
                lat: "10.346704530854",
                type: 2,
                created_at: null,
                updated_at: null
            }
        ],
        trip_location: [
            {
                id: 3,
                trip_id: 2,
                address_id: null,
                address: "cong ty",
                province_id: null,
                province_name: null,
                district_id: null,
                district_name: null,
                ward_id: null,
                ward_name: null,
                lng: "106.68155700938",
                lat: "10.752641387071",
                type: 1,
                created_at: null,
                updated_at: null
            },
            {
                id: 4,
                trip_id: 2,
                address_id: null,
                address: "Nha tui",
                province_id: null,
                province_name: null,
                district_id: null,
                district_name: null,
                ward_id: null,
                ward_name: null,
                lng: "107.09812511097",
                lat: "10.346704530854",
                type: 2,
                created_at: null,
                updated_at: null
            }
        ],
        driver: {
            id: 6,
            reference: "GC04NDQEZ",
            phone: "0974564412",
            name: "Nguyen van C",
            sex: 0,
            birth_date: null,
            total_trip: 0,
            total_use_point: 0,
            level: 0,
            level_point: 0,
            status: 2,
            type: 1,
            medias: [],
            uuid: "9a9fbb66-01fd-4275-bfdd-3e04189c2cc1",
            email: null,
            driver_type: 1,
            citizen_identify: "038343509901",
            citizen_name: "Nguyen",
            citizen_issued_date: "2021-12-21",
            citizen_expire_date: "2024-12-21",
            driver_license: "038343509901",
            driver_name: "Nguyen",
            driver_class: "A1",
            driver_issued_date: "2003-03-08",
            driver_expire_date: null,
            support_phone: null,
            support_name: null,
            created_at: "2023-11-16T04:19:05.000000Z",
            updated_at: "2023-12-07T04:14:23.000000Z",
            rating_averate: 4,
            total_ratings: 1,
            is_submit_form: true,
            place_of_origin: "Tp Ho Chi Minh",
            place_of_residence: "728 Võ Văn Kiệt, phường 1, quận 5, TPHCM",
            is_receive_ride: true,
            vehicle: {
                id: 1,
                driver_id: 6,
                vehicle_brand_id: 1,
                vehicle_type_id: 1,
                driver_phone: "0974564412",
                driver_reference: "GC04NDQEZ",
                name: null,
                description: null,
                reference: "GC04NDQEZ_VH_0001",
                is_owner: 1,
                license_plates: "60B8-04544",
                registration_certificate: "026253",
                frame_number: "808AY-218896",
                engine_number: "F27E-0259146",
                brand_name: "Honda",
                model_name: "AirBlade",
                model_years: 2010,
                color: "Đen-Xám",
                seats: 2,
                insurance_civil_accident_date: "2021-12-21",
                insurance_civil_accident_price: 50000,
                insurance_vehicle_material_date: "2021-12-21",
                insurance_vehicle_material_price: 50000,
                cudidi_insurance_civil_accident_date: null,
                cudidi_insurance_vehicle_material_date: null,
                type: 1,
                status: 1,
                medias: null,
                created_at: "2023-11-29T10:53:05.000000Z",
                updated_at: "2023-11-29T10:53:05.000000Z",
                deleted_at: null
            },
            status_name: "Bổ sung hồ sơ",
            driver_type_name: "Xe máy"
        },
        passenger: {
            id: 2,
            reference: "785694",
            phone: "0909111111",
            name: null,
            sex: null,
            birth_date: null,
            level: 0,
            level_point: 0,
            status: 0,
            type: 1,
            medias: [],
            created_at: "2023-11-09T08:17:46.000000Z",
            updated_at: "2023-12-15T10:26:20.000000Z",
            uuid: null,
            email: null,
            token_location: null,
            token_at: null
        }
    },
    {
        id: 4,
        passenger_id: 3,
        driver_id: 6,
        trip_id: 3,
        rating: 5,
        notes: null,
        on_time: false,
        professional: false,
        devoted: false,
        clean: false,
        deleted_at: null,
        created_at: null,
        updated_at: null,
        trip: {
            id: 3,
            passenger_id: 3,
            passenger_name: null,
            passenger_phone: "0909111114",
            driver_id: null,
            driver_name: null,
            driver_phone: "0974564412",
            reference: "TR000003",
            vehicle_id: null,
            product_id: null,
            product_name: null,
            notes: null,
            type: null,
            status: 7,
            total: null,
            total_discount: null,
            total_distance: 103067,
            total_duration: 9093,
            total_paid: 428000,
            deleted_at: null,
            created_at: "2023-11-21T08:15:27.000000Z",
            updated_at: "2023-11-21T09:09:01.000000Z",
            cancel_type: null,
            payment_type: 1,
            passenger_uuid: null,
            driver_uuid: null,
            total_insurance: null,
            trip_locations: [
                {
                    id: 5,
                    trip_id: 3,
                    address_id: null,
                    address: "cong ty",
                    province_id: null,
                    province_name: null,
                    district_id: null,
                    district_name: null,
                    ward_id: null,
                    ward_name: null,
                    lng: "106.68155700938",
                    lat: "10.752641387071",
                    type: 1,
                    created_at: null,
                    updated_at: null
                },
                {
                    id: 6,
                    trip_id: 3,
                    address_id: null,
                    address: "Nha tui",
                    province_id: null,
                    province_name: null,
                    district_id: null,
                    district_name: null,
                    ward_id: null,
                    ward_name: null,
                    lng: "107.09812511097",
                    lat: "10.346704530854",
                    type: 2,
                    created_at: null,
                    updated_at: null
                }
            ],
            trip_vehicle_types: [
                {
                    id: 9,
                    trip_id: 3,
                    vehicle_type_id: 1,
                    price: 428000,
                    distance: 103067,
                    duration: 9093,
                    total_price: null,
                    type: null,
                    status: null,
                    created_at: "2023-11-21T08:15:28.000000Z",
                    updated_at: "2023-11-21T08:15:28.000000Z",
                }
            ]
        },
        trip_locations: [],
        trip_vehicle_type: [
            {
                id: 5,
                trip_id: 3,
                address_id: null,
                address: "cong ty",
                province_id: null,
                province_name: null,
                district_id: null,
                district_name: null,
                ward_id: null,
                ward_name: null,
                lng: "106.68155700938",
                lat: "10.752641387071",
                type: 1,
                created_at: null,
                updated_at: null
            },
            {
                id: 6,
                trip_id: 3,
                address_id: null,
                address: "Nha tui",
                province_id: null,
                province_name: null,
                district_id: null,
                district_name: null,
                ward_id: null,
                ward_name: null,
                lng: "107.09812511097",
                lat: "10.346704530854",
                type: 2,
                created_at: null,
                updated_at: null
            }
        ],
        trip_location: [
            {
                id: 5,
                trip_id: 3,
                address_id: null,
                address: "cong ty",
                province_id: null,
                province_name: null,
                district_id: null,
                district_name: null,
                ward_id: null,
                ward_name: null,
                lng: "106.68155700938",
                lat: "10.752641387071",
                type: 1,
                created_at: null,
                updated_at: null
            },
            {
                id: 6,
                trip_id: 3,
                address_id: null,
                address: "Nha tui",
                province_id: null,
                province_name: null,
                district_id: null,
                district_name: null,
                ward_id: null,
                ward_name: null,
                lng: "107.09812511097",
                lat: "10.346704530854",
                type: 2,
                created_at: null,
                updated_at: null
            }
        ],
        driver: {
            id: 6,
            reference: "GC04NDQEZ",
            phone: "0974564412",
            name: "Nguyen van C",
            sex: 0,
            birth_date: null,
            total_trip: 0,
            total_use_point: 0,
            level: 0,
            level_point: 0,
            status: 2,
            type: 1,
            medias: [],
            uuid: "9a9fbb66-01fd-4275-bfdd-3e04189c2cc1",
            email: null,
            driver_type: 1,
            citizen_identify: "038343509901",
            citizen_name: "Nguyen",
            citizen_issued_date: "2021-12-21",
            citizen_expire_date: "2024-12-21",
            driver_license: "038343509901",
            driver_name: "Nguyen",
            driver_class: "A1",
            driver_issued_date: "2003-03-08",
            driver_expire_date: null,
            support_phone: null,
            support_name: null,
            created_at: "2023-11-16T04:19:05.000000Z",
            updated_at: "2023-12-07T04:14:23.000000Z",
            rating_averate: 4,
            total_ratings: 1,
            is_submit_form: true,
            place_of_origin: "Tp Ho Chi Minh",
            place_of_residence: "728 Võ Văn Kiệt, phường 1, quận 5, TPHCM",
            is_receive_ride: true,
            vehicle: {
                id: 1,
                driver_id: 6,
                vehicle_brand_id: 1,
                vehicle_type_id: 1,
                driver_phone: "0974564412",
                driver_reference: "GC04NDQEZ",
                name: null,
                description: null,
                reference: "GC04NDQEZ_VH_0001",
                is_owner: 1,
                license_plates: "60B8-04544",
                registration_certificate: "026253",
                frame_number: "808AY-218896",
                engine_number: "F27E-0259146",
                brand_name: "Honda",
                model_name: "AirBlade",
                model_years: 2010,
                color: "Đen-Xám",
                seats: 2,
                insurance_civil_accident_date: "2021-12-21",
                insurance_civil_accident_price: 50000,
                insurance_vehicle_material_date: "2021-12-21",
                insurance_vehicle_material_price: 50000,
                cudidi_insurance_civil_accident_date: null,
                cudidi_insurance_vehicle_material_date: null,
                type: 1,
                status: 1,
                medias: null,
                created_at: "2023-11-29T10:53:05.000000Z",
                updated_at: "2023-11-29T10:53:05.000000Z",
                deleted_at: null
            },
            status_name: "Bổ sung hồ sơ",
            driver_type_name: "Xe máy"
        },
        passenger: {
            id: 3,
            reference: "027569",
            phone: "0909111114",
            name: null,
            sex: null,
            birth_date: null,
            level: 0,
            level_point: 0,
            status: 1,
            type: 1,
            medias: [
                {
                    id: 113,
                    path: "https://test.api.cuvietnam.com.vn/mediaService/storage/passengers/1700737342_Sk3iC9GsLojKsuXTMwmr11eSrVSPUsWQ8ZH7NZ35.jpg",
                    type: "cover"
                }
            ],
            created_at: "2023-11-13T09:43:23.000000Z",
            updated_at: "2023-12-18T06:28:34.000000Z",
            uuid: "9a9a266d-d517-4259-baae-c33cb0d0230b",
            email: null
        }
    }
]
