name: Build and Push Docker image to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: ${{ secrets.APP_NAME }}
      APP_ENV: ${{ secrets.APP_ENV }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_DEBUG: ${{ secrets.APP_DEBUG }}
      APP_URL: ${{ secrets.APP_URL }}
      LOG_CHANNEL: ${{ secrets.LOG_CHANNEL }}
      LOG_DEPRECATIONS_CHANNEL: ${{ secrets.LOG_DEPRECATIONS_CHANNEL }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      BROADCAST_DRIVER: ${{ secrets.BROADCAST_DRIVER }}
      CACHE_DRIVER: ${{ secrets.CACHE_DRIVER }}
      FILESYSTEM_DISK: ${{ secrets.FILESYSTEM_DISK }}
      QUEUE_CONNECTION: ${{ secrets.QUEUE_CONNECTION }}
      SESSION_DRIVER: ${{ secrets.SESSION_DRIVER }}
      SESSION_LIFETIME: ${{ secrets.SESSION_LIFETIME }}
      MEMCACHED_HOST: ${{ secrets.MEMCACHED_HOST }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      MAIL_MAILER: ${{ secrets.MAIL_MAILER }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_ENCRYPTION: ${{ secrets.MAIL_ENCRYPTION }}
      MAIL_FROM_ADDRESS: ${{ secrets.MAIL_FROM_ADDRESS }}
      MAIL_FROM_NAME: ${{ secrets.MAIL_FROM_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_USE_PATH_STYLE_ENDPOINT: ${{ secrets.AWS_USE_PATH_STYLE_ENDPOINT }}
      PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
      PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
      PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
      PUSHER_HOST: ${{ secrets.PUSHER_HOST }}
      PUSHER_PORT: ${{ secrets.PUSHER_PORT }}
      PUSHER_SCHEME: ${{ secrets.PUSHER_SCHEME }}
      PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_APP_CLUSTER }}
      VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}
      VITE_PUSHER_APP_KEY: ${{ secrets.VITE_PUSHER_APP_KEY }}
      VITE_PUSHER_HOST: ${{ secrets.VITE_PUSHER_HOST }}
      VITE_PUSHER_PORT: ${{ secrets.VITE_PUSHER_PORT }}
      VITE_PUSHER_SCHEME: ${{ secrets.VITE_PUSHER_SCHEME }}
      VITE_PUSHER_APP_CLUSTER: ${{ secrets.VITE_PUSHER_APP_CLUSTER }}
      SCOUT_DRIVER: ${{ secrets.SCOUT_DRIVER }}
      MEILISEARCH_HOST: ${{ secrets.MEILISEARCH_HOST }}
      MEILISEARCH_NO_ANALYTICS: ${{ secrets.MEILISEARCH_NO_ANALYTICS }}
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: ${{ secrets.PHP_OPCACHE_VALIDATE_TIMESTAMPS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml push
